// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjx3mujCzYDlHoJfB98LFTmq3KM6_vVF8',
    appId: '1:472318160609:web:bbe434dc4525a91cb211a0',
    messagingSenderId: '472318160609',
    projectId: 'education-app-8a71d',
    authDomain: 'education-app-8a71d.firebaseapp.com',
    storageBucket: 'education-app-8a71d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRDRsPQtLR4gFfo69kVHSnCCHFpKs-JC0',
    appId: '1:472318160609:android:763fae01798949eeb211a0',
    messagingSenderId: '472318160609',
    projectId: 'education-app-8a71d',
    storageBucket: 'education-app-8a71d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT8pFBzCYh9muJxa4D3MWuXe6M0pXnqhM',
    appId: '1:472318160609:ios:0902d1c27ec1eed5b211a0',
    messagingSenderId: '472318160609',
    projectId: 'education-app-8a71d',
    storageBucket: 'education-app-8a71d.appspot.com',
    iosBundleId: 'com.example.educationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT8pFBzCYh9muJxa4D3MWuXe6M0pXnqhM',
    appId: '1:472318160609:ios:fa7b76030fa582e0b211a0',
    messagingSenderId: '472318160609',
    projectId: 'education-app-8a71d',
    storageBucket: 'education-app-8a71d.appspot.com',
    iosBundleId: 'com.example.educationApp.RunnerTests',
  );
}
